# Generated by Django 5.2.17 on 2026-09-23 17:42
# ruff: noqa: RUF012 - Django generates mutable migration operations.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("display_order", models.PositiveSmallIntegerField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=11,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("overall_band", models.CharField(max_length=12)),
                ("scoring_version", models.CharField(max_length=32)),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="assessments.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PillarResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("band", models.CharField(max_length=12)),
                (
                    "assessment_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pillars",
                        to="assessments.assessmentresult",
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.pillar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnairePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.pillar",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("text", models.TextField()),
                ("required", models.BooleanField(default=True)),
                ("scorable", models.BooleanField(default=True)),
                (
                    "score_direction",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("REVERSE", "Reverse")],
                        default="NORMAL",
                        max_length=7,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=8)),
                ("display_order", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "questionnaire_pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.questionnairepillar",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("scoring_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"),
                        name="assessment_questionnaire_code_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="assessment_questionnaire_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["DRAFT", "PUBLISHED", "RETIRED"])
                        ),
                        name="assessment_questionnaire_valid_status",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="questionnairepillar",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pillars",
                to="assessments.questionnaireversion",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="questionnaire_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="assessments.questionnaireversion",
            ),
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("score_value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("display_order", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.questionoption",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assessmentresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("overall_score__gte", 0), ("overall_score__lte", 100)
                ),
                name="assessment_overall_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pillarresult",
            constraint=models.UniqueConstraint(
                fields=("assessment_result", "pillar"),
                name="assessment_result_pillar_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="pillarresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="assessment_pillar_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("questionnaire_pillar", "code"),
                name="assessment_question_pillar_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("questionnaire_pillar", "display_order"),
                name="assessment_question_pillar_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)),
                name="assessment_question_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("score_direction__in", ["NORMAL", "REVERSE"])),
                name="assessment_question_valid_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnairepillar",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "pillar"),
                name="assessment_version_pillar_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnairepillar",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "display_order"),
                name="assessment_version_pillar_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnairepillar",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)),
                name="assessment_pillar_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["IN_PROGRESS", "COMPLETED"])),
                name="assessment_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", True), ("status", "IN_PROGRESS")),
                    models.Q(("completed_at__isnull", False), ("status", "COMPLETED")),
                    _connector="OR",
                ),
                name="assessment_completion_timestamp_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "code"),
                name="assessment_option_question_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "display_order"),
                name="assessment_option_question_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.CheckConstraint(
                condition=models.Q(("score_value__gte", 0), ("score_value__lte", 100)),
                name="assessment_option_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("assessment", "question"),
                name="assessment_one_answer_per_question",
            ),
        ),
    ]
