# Generated by Django 5.2.17 on 2026-09-23 17:58
# ruff: noqa: RUF012 - Django generates mutable migration operations.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_integrity_triggers"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pillar",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_order__gte", 1), ("display_order__lte", 9)
                ),
                name="assessment_pillar_order_nine_range",
            ),
        ),
    ]
